<script setup lang="ts">
import { ArrowLeft, Pencil, Plus, Save, Sparkles, Trash2, X } from "lucide-vue-next";
type Role = "damage" | "buff";
type Behavior = "bonus_damage" | "critical_hit" | "damage_over_time" | "slow" | "splash_damage" | "damage_aura" | "attack_speed_aura";
interface EffectType { id:string; name:string; role:Role; behavior:Behavior; description:string|null; color:string; sort_order:number; is_active:boolean }
const behaviors:Array<{value:Behavior;label:string;role:Role;help:string}>=[{value:"bonus_damage",label:"Cộng sát thương",role:"damage",help:"Cộng giá trị vào mỗi đòn đánh."},{value:"critical_hit",label:"Chí mạng",role:"damage",help:"Cho mỗi đòn cơ hội nhân sát thương theo hệ số cấu hình."},{value:"damage_over_time",label:"Sát thương theo thời gian",role:"damage",help:"Gây sát thương mỗi giây trong thời lượng cấu hình."},{value:"slow",label:"Làm chậm",role:"damage",help:"Giảm tốc độ di chuyển của mục tiêu."},{value:"splash_damage",label:"Sát thương lan",role:"damage",help:"Phân phối sát thương trong bán kính quanh mục tiêu."},{value:"damage_aura",label:"Buff sát thương",role:"buff",help:"Tăng sát thương tower đồng minh trong vùng."},{value:"attack_speed_aura",label:"Buff tốc đánh",role:"buff",help:"Tăng tốc đánh tower đồng minh trong vùng."}];
const route=useRoute();const router=useRouter();const api=useApi();const routeId=computed(()=>String(route.params.effectTypeId));const isCreating=computed(()=>routeId.value==="new");const items=ref<EffectType[]>([]);const loading=ref(true);const saving=ref(false);const error=ref("");const editingId=ref<string|null>(null);const page=ref(1);const lastPage=ref(1);const total=ref(0);
const blank=()=>({id:"",name:"",role:"damage" as Role,behavior:"bonus_damage" as Behavior,description:"",color:"#8b5cf6",sortOrder:0,isActive:true});const form=reactive(blank());
const availableBehaviors=computed(()=>behaviors.filter(item=>item.role===form.role));const selectedBehavior=computed(()=>behaviors.find(item=>item.value===form.behavior));
async function load(targetPage=page.value){loading.value=true;try{const response=await api<{data:EffectType[];current_page:number;last_page:number;total:number}>(`/api/admin/tower-defense/effect-types?per_page=500&page=${targetPage}`);items.value=response.data;page.value=response.current_page;lastPage.value=response.last_page;total.value=response.total}catch(e:any){error.value=e?.data?.message||"Không thể tải loại hiệu ứng."}finally{loading.value=false}}
async function loadEditor(){await load(1);if(error.value)return;if(isCreating.value){editingId.value=null;Object.assign(form,blank());return}const item=items.value.find(entry=>entry.id===routeId.value);if(!item){error.value="Không tìm thấy loại hiệu ứng.";return}editingId.value=item.id;Object.assign(form,{id:item.id,name:item.name,role:item.role,behavior:item.behavior,description:item.description??"",color:item.color,sortOrder:item.sort_order,isActive:item.is_active})}
async function save(){saving.value=true;error.value="";try{await api(`/api/admin/tower-defense/effect-types${editingId.value?`/${editingId.value}`:""}`,{method:editingId.value?"PUT":"POST",body:{id:form.id,name:form.name,role:form.role,behavior:form.behavior,description:form.description||null,color:form.color,sort_order:Number(form.sortOrder),is_active:form.isActive}});await router.push("/admin/tower-defense/effect-types")}catch(e:any){error.value=e?.data?.message||"Không thể lưu loại hiệu ứng."}finally{saving.value=false}}
async function remove(item:EffectType){if(!confirm(`Xóa loại hiệu ứng “${item.name}”?`))return;await api(`/api/admin/tower-defense/effect-types/${item.id}`,{method:"DELETE"});await load()}
watch(()=>form.role,()=>{if(!availableBehaviors.value.some(item=>item.value===form.behavior))form.behavior=availableBehaviors.value[0]!.value});useHead(()=>({title:isCreating.value?"Tạo hiệu ứng Tower | Admin":"Sửa hiệu ứng Tower | Admin"}));onMounted(loadEditor);
</script>
<template><main class="effect-type-page effect-editor-page"><header class="page-head"><div><NuxtLink to="/admin/tower-defense/towers"><ArrowLeft/> Quản lý tower</NuxtLink><small>TOWER EFFECT ENGINE</small><h1>{{isCreating?"Tạo hiệu ứng trụ":"Chỉnh sửa hiệu ứng trụ"}}</h1><p>Định nghĩa cách hiệu ứng xuất hiện và hoạt động trong gameplay.</p></div><NuxtLink class="effect-back-link" to="/admin/tower-defense/effect-types"><ArrowLeft/> Danh sách hiệu ứng</NuxtLink></header><div v-if="loading" class="empty">Đang tải…</div><p v-if="error" class="alert">{{error}}</p><section v-if="!loading && (isCreating || editingId)" class="effect-editor-card"><form @submit.prevent="save"><header><div><Sparkles/><span><small>{{isCreating?'TẠO MỚI':'CHỈNH SỬA'}}</small><h2>{{form.name||"Loại hiệu ứng mới"}}</h2></span></div></header><div class="form"><label><span>Mã loại</span><input v-model="form.id" :disabled="!isCreating" required pattern="[a-z0-9-]+" placeholder="poison"/><small>Dùng chữ thường, số và dấu gạch ngang.</small></label><label><span>Tên hiển thị</span><input v-model="form.name" required placeholder="Độc tố"/></label><label><span>Nhóm tower</span><select v-model="form.role"><option value="damage">Gây sát thương</option><option value="buff">Hỗ trợ / Buff</option></select></label><label><span>Hành vi frontend</span><select v-model="form.behavior"><option v-for="behavior in availableBehaviors" :key="behavior.value" :value="behavior.value">{{behavior.label}}</option></select><small>{{selectedBehavior?.help}}</small></label><label><span>Màu mặc định</span><input v-model="form.color" type="color"/></label><label><span>Thứ tự</span><input v-model.number="form.sortOrder" type="number" min="0"/></label><label class="wide"><span>Mô tả</span><textarea v-model="form.description" rows="4"/></label><label class="check"><input v-model="form.isActive" type="checkbox"/> Cho phép chọn trong tower</label></div><footer><NuxtLink class="effect-cancel-link" to="/admin/tower-defense/effect-types">Hủy</NuxtLink><button class="primary" type="submit" :disabled="saving"><Save/> {{saving?'Đang lưu…':isCreating?'Tạo hiệu ứng':'Lưu thay đổi'}}</button></footer></form></section></main></template>
<style scoped src="~/assets/css/pages/admin/tower-defense-effect-types.css"></style>
