<script setup lang="ts">
import { ArrowLeft, Pencil, Plus, Save, Sparkles, Trash2, X } from "lucide-vue-next";
type Role = "damage" | "buff";
type Behavior = "bonus_damage" | "damage_over_time" | "slow" | "splash_damage" | "damage_aura" | "attack_speed_aura";
interface EffectType { id:string; name:string; role:Role; behavior:Behavior; description:string|null; color:string; sort_order:number; is_active:boolean }
const behaviors:Array<{value:Behavior;label:string;role:Role;help:string}>=[{value:"bonus_damage",label:"Cộng sát thương",role:"damage",help:"Cộng giá trị vào mỗi đòn đánh."},{value:"damage_over_time",label:"Sát thương theo thời gian",role:"damage",help:"Gây sát thương mỗi giây trong thời lượng cấu hình."},{value:"slow",label:"Làm chậm",role:"damage",help:"Giảm tốc độ di chuyển của mục tiêu."},{value:"splash_damage",label:"Sát thương lan",role:"damage",help:"Phân phối sát thương trong bán kính quanh mục tiêu."},{value:"damage_aura",label:"Buff sát thương",role:"buff",help:"Tăng sát thương tower đồng minh trong vùng."},{value:"attack_speed_aura",label:"Buff tốc đánh",role:"buff",help:"Tăng tốc đánh tower đồng minh trong vùng."}];
const api=useApi();const items=ref<EffectType[]>([]);const loading=ref(true);const saving=ref(false);const error=ref("");const dialog=ref<HTMLDialogElement|null>(null);const editingId=ref<string|null>(null);const page=ref(1);const lastPage=ref(1);const total=ref(0);
const blank=()=>({id:"",name:"",role:"damage" as Role,behavior:"bonus_damage" as Behavior,description:"",color:"#8b5cf6",sortOrder:0,isActive:true});const form=reactive(blank());
const availableBehaviors=computed(()=>behaviors.filter(item=>item.role===form.role));const selectedBehavior=computed(()=>behaviors.find(item=>item.value===form.behavior));
async function load(targetPage=page.value){loading.value=true;try{const response=await api<{data:EffectType[];current_page:number;last_page:number;total:number}>(`/api/admin/tower-defense/effect-types?per_page=12&page=${targetPage}`);items.value=response.data;page.value=response.current_page;lastPage.value=response.last_page;total.value=response.total}catch(e:any){error.value=e?.data?.message||"Không thể tải loại hiệu ứng."}finally{loading.value=false}}
function createItem(){editingId.value=null;Object.assign(form,blank());dialog.value?.showModal()}function editItem(item:EffectType){editingId.value=item.id;Object.assign(form,{id:item.id,name:item.name,role:item.role,behavior:item.behavior,description:item.description??"",color:item.color,sortOrder:item.sort_order,isActive:item.is_active});dialog.value?.showModal()}
async function save(){saving.value=true;error.value="";try{await api(`/api/admin/tower-defense/effect-types${editingId.value?`/${editingId.value}`:""}`,{method:editingId.value?"PUT":"POST",body:{id:form.id,name:form.name,role:form.role,behavior:form.behavior,description:form.description||null,color:form.color,sort_order:Number(form.sortOrder),is_active:form.isActive}});dialog.value?.close();await load()}catch(e:any){error.value=e?.data?.message||"Không thể lưu loại hiệu ứng."}finally{saving.value=false}}
async function remove(item:EffectType){if(!confirm(`Xóa loại hiệu ứng “${item.name}”?`))return;await api(`/api/admin/tower-defense/effect-types/${item.id}`,{method:"DELETE"});await load()}
watch(()=>form.role,()=>{if(!availableBehaviors.value.some(item=>item.value===form.behavior))form.behavior=availableBehaviors.value[0]!.value});useHead({title:"Loại hiệu ứng Tower | Admin"});onMounted(load);
</script>
<template><main class="effect-type-page"><header class="page-head"><div><NuxtLink to="/admin/tower-defense/towers"><ArrowLeft/> Quản lý tower</NuxtLink><small>TOWER EFFECT ENGINE</small><h1>Loại hiệu ứng</h1><p>Tạo hiệu ứng mới dựa trên hành vi gameplay frontend hỗ trợ.</p></div><button class="primary" @click="createItem"><Plus/> Thêm loại hiệu ứng</button></header><p v-if="error" class="alert">{{error}}</p><div v-if="loading" class="empty">Đang tải…</div><template v-else><section class="effect-grid"><article v-for="item in items" :key="item.id" :class="{inactive:!item.is_active}"><i :style="{background:item.color}"/><header><small>{{item.role==='buff'?'BUFF':'DAMAGE'}}</small><h2>{{item.name}}</h2><code>{{item.id}}</code></header><p>{{item.description}}</p><dl><dt>Hành vi frontend</dt><dd>{{behaviors.find(entry=>entry.value===item.behavior)?.label}}</dd></dl><footer><button @click="editItem(item)"><Pencil/> Sửa</button><button class="danger" @click="remove(item)"><Trash2/></button></footer></article></section><AdminPagination :page="page" :last-page="lastPage" :total="total" :loading="loading" @change="load" /></template><dialog ref="dialog" @click.self="dialog?.close()"><form @submit.prevent="save"><header><div><Sparkles/><span><small>{{editingId?'CHỈNH SỬA':'TẠO MỚI'}}</small><h2>Loại hiệu ứng</h2></span></div><button type="button" @click="dialog?.close()"><X/></button></header><div class="form"><label><span>Mã loại</span><input v-model="form.id" :disabled="!!editingId" required placeholder="poison"/></label><label><span>Tên hiển thị</span><input v-model="form.name" required placeholder="Độc tố"/></label><label><span>Nhóm tower</span><select v-model="form.role"><option value="damage">Gây sát thương</option><option value="buff">Hỗ trợ / Buff</option></select></label><label><span>Hành vi frontend</span><select v-model="form.behavior"><option v-for="behavior in availableBehaviors" :key="behavior.value" :value="behavior.value">{{behavior.label}}</option></select><small>{{selectedBehavior?.help}}</small></label><label><span>Màu mặc định</span><input v-model="form.color" type="color"/></label><label><span>Thứ tự</span><input v-model.number="form.sortOrder" type="number" min="0"/></label><label class="wide"><span>Mô tả</span><textarea v-model="form.description" rows="3"/></label><label class="check"><input v-model="form.isActive" type="checkbox"/> Cho phép chọn trong tower</label></div><footer><button type="button" @click="dialog?.close()">Hủy</button><button class="primary" :disabled="saving"><Save/> {{saving?'Đang lưu…':'Lưu loại hiệu ứng'}}</button></footer></form></dialog></main></template>
<style scoped src="~/assets/css/pages/admin/tower-defense-effect-types.css"></style>
