<script setup lang="ts">
import { ArrowLeft, Pencil, Plus, Save, Sparkles, Trash2, X } from "lucide-vue-next";
type Role = "damage" | "buff";
type Behavior = "bonus_damage" | "critical_hit" | "damage_over_time" | "slow" | "splash_damage" | "damage_aura" | "attack_speed_aura";
interface EffectType { id:string; name:string; role:Role; behavior:Behavior; description:string|null; color:string; sort_order:number; is_active:boolean }
const behaviors:Array<{value:Behavior;label:string;role:Role;help:string}>=[{value:"bonus_damage",label:"Cộng sát thương",role:"damage",help:"Cộng giá trị vào mỗi đòn đánh."},{value:"critical_hit",label:"Chí mạng",role:"damage",help:"Cho mỗi đòn cơ hội nhân sát thương theo hệ số cấu hình."},{value:"damage_over_time",label:"Sát thương theo thời gian",role:"damage",help:"Gây sát thương mỗi giây trong thời lượng cấu hình."},{value:"slow",label:"Làm chậm",role:"damage",help:"Giảm tốc độ di chuyển của mục tiêu."},{value:"splash_damage",label:"Sát thương lan",role:"damage",help:"Phân phối sát thương trong bán kính quanh mục tiêu."},{value:"damage_aura",label:"Buff sát thương",role:"buff",help:"Tăng sát thương tower đồng minh trong vùng."},{value:"attack_speed_aura",label:"Buff tốc đánh",role:"buff",help:"Tăng tốc đánh tower đồng minh trong vùng."}];
const api=useApi();const items=ref<EffectType[]>([]);const loading=ref(true);const error=ref("");const page=ref(1);const lastPage=ref(1);const total=ref(0);
const blank=()=>({id:"",name:"",role:"damage" as Role,behavior:"bonus_damage" as Behavior,description:"",color:"#8b5cf6",sortOrder:0,isActive:true});const form=reactive(blank());
const availableBehaviors=computed(()=>behaviors.filter(item=>item.role===form.role));const selectedBehavior=computed(()=>behaviors.find(item=>item.value===form.behavior));
async function load(targetPage=page.value){loading.value=true;try{const response=await api<{data:EffectType[];current_page:number;last_page:number;total:number}>(`/api/admin/tower-defense/effect-types?per_page=12&page=${targetPage}`);items.value=response.data;page.value=response.current_page;lastPage.value=response.last_page;total.value=response.total}catch(e:any){error.value=e?.data?.message||"Không thể tải loại hiệu ứng."}finally{loading.value=false}}
async function remove(item:EffectType){if(!confirm(`Xóa loại hiệu ứng “${item.name}”?`))return;await api(`/api/admin/tower-defense/effect-types/${item.id}`,{method:"DELETE"});await load()}
useHead({title:"Loại hiệu ứng Tower | Admin"});onMounted(load);
</script>
<template><main class="effect-type-page"><header class="page-head"><div><NuxtLink to="/admin/tower-defense/towers"><ArrowLeft/> Quản lý tower</NuxtLink><small>TOWER EFFECT ENGINE</small><h1>Loại hiệu ứng</h1><p>Tạo hiệu ứng mới dựa trên hành vi gameplay frontend hỗ trợ.</p></div><NuxtLink class="primary effect-create-link" to="/admin/tower-defense/effect-types/new"><Plus/> Thêm loại hiệu ứng</NuxtLink></header><p v-if="error" class="alert">{{error}}</p><div v-if="loading" class="empty">Đang tải…</div><template v-else><section class="effect-grid"><article v-for="item in items" :key="item.id" :class="{inactive:!item.is_active}"><i :style="{background:item.color}"/><header><small>{{item.role==='buff'?'BUFF':'DAMAGE'}}</small><h2>{{item.name}}</h2><code>{{item.id}}</code></header><p>{{item.description}}</p><dl><dt>Hành vi frontend</dt><dd>{{behaviors.find(entry=>entry.value===item.behavior)?.label}}</dd></dl><footer><NuxtLink class="effect-edit-link" :to="'/admin/tower-defense/effect-types/'+item.id"><Pencil/> Sửa</NuxtLink><button class="danger" @click="remove(item)"><Trash2/></button></footer></article></section><AdminPagination :page="page" :last-page="lastPage" :total="total" :loading="loading" @change="load" /></template></main></template>
<style scoped src="~/assets/css/pages/admin/tower-defense-effect-types.css"></style>
